"use client";

import { useEffect, useState } from "react";
import api from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import {
  Sparkles,
  MessageSquare,
  Lightbulb,
  CheckCircle2,
  Info,
  RefreshCw,
} from "lucide-react";
import { Button } from "@/components/ui/button";

export default function ConversationGuideBox({ customerId }) {
  const [guide, setGuide] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    if (customerId) {
      fetchConversationGuide();
    }
  }, [customerId]);

  const fetchConversationGuide = async () => {
    try {
      setLoading(true);
      setError("");
      const response = await api.conversationGuide.get(customerId);
      setGuide(response.data.guide);
    } catch (err) {
      setError(err.message || "Failed to load conversation guide");
      console.error("Error fetching conversation guide:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleRefresh = () => {
    fetchConversationGuide();
  };

  if (loading) {
    return (
      <Card className="border-border/50 shadow-elevated">
        <CardHeader className="bg-linear-to-r from-purple-50 to-blue-50">
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-purple-600" />
            Panduan Percakapan AI
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-6 space-y-4">
          <Skeleton className="h-20 w-full" />
          <Skeleton className="h-32 w-full" />
          <Skeleton className="h-24 w-full" />
          <Skeleton className="h-20 w-full" />
        </CardContent>
      </Card>
    );
  }

  if (error) {
    return (
      <Card className="border-border/50 shadow-elevated">
        <CardHeader className="bg-linear-to-r">
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-purple-600" />
            Panduan Percakapan AI
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-6">
          <div className="text-center py-8">
            <div className="text-red-500 mb-4">
              <svg
                className="w-12 h-12 mx-auto"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
            </div>
            <p className="text-sm text-muted-foreground mb-4">{error}</p>
            <Button onClick={handleRefresh} size="sm" variant="outline">
              <RefreshCw className="w-4 h-4 mr-2" />
              Try Again
            </Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (!guide) return null;

  return (
    <Card className="border-border/50 shadow-elevated overflow-hidden">
      <CardHeader className="bg-linear-to-r from-purple-50 to-blue-50 border-b">
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-purple-600 animate-pulse" />
            Panduan Percakapan AI
          </CardTitle>
          <Button
            onClick={handleRefresh}
            size="sm"
            variant="ghost"
            className="h-8 w-8 p-0"
            title="Refresh panduan"
          >
            <RefreshCw className="w-4 h-4" />
          </Button>
        </div>
        {guide.generatedBy === "ai" ? (
          <Badge
            variant="outline"
            className="w-fit bg-purple-100 text-purple-700 border-purple-200"
          >
            <Sparkles className="w-3 h-3 mr-1" />
            Generated by Gemini AI
          </Badge>
        ) : (
          <Badge
            variant="outline"
            className="w-fit bg-gray-100 text-gray-700 border-gray-200"
          >
            <Info className="w-3 h-3 mr-1" />
            Template Guide
          </Badge>
        )}
      </CardHeader>
      <CardContent className="pt-6 space-y-6 max-h-[600px] overflow-y-auto">
        {/* Opening Section */}
        <div className="space-y-2">
          <div className="flex items-center gap-2 mb-2">
            <div className="p-2 rounded-lg bg-green-100">
              <MessageSquare className="w-4 h-4 text-green-700" />
            </div>
            <h3 className="font-semibold text-sm">Pembukaan</h3>
          </div>
          <div className="p-4 rounded-lg bg-green-50 border border-green-200">
            <p className="text-sm text-green-900 leading-relaxed italic">
              "{guide.opening}"
            </p>
          </div>
        </div>

        {/* Topics Section */}
        <div className="space-y-2">
          <div className="flex items-center gap-2 mb-2">
            <div className="p-2 rounded-lg bg-blue-100">
              <Lightbulb className="w-4 h-4 text-blue-700" />
            </div>
            <h3 className="font-semibold text-sm">Topik Percakapan</h3>
          </div>
          <ul className="space-y-2">
            {guide.topics.map((topic, index) => (
              <li
                key={index}
                className="flex items-start gap-2 p-3 rounded-lg bg-blue-50 border border-blue-200"
              >
                <CheckCircle2 className="w-4 h-4 text-blue-700 mt-0.5 shrink-0" />
                <span className="text-sm text-blue-900">{topic}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Key Points Section */}
        <div className="space-y-2">
          <div className="flex items-center gap-2 mb-2">
            <div className="p-2 rounded-lg bg-orange-100">
              <Info className="w-4 h-4 text-orange-700" />
            </div>
            <h3 className="font-semibold text-sm">Poin Penting</h3>
          </div>
          <ul className="space-y-2">
            {guide.keyPoints.map((point, index) => (
              <li
                key={index}
                className="flex items-start gap-2 p-3 rounded-lg bg-orange-50 border border-orange-200"
              >
                <span className="text-orange-700 font-bold shrink-0">•</span>
                <span className="text-sm text-orange-900">{point}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Closing Section */}
        <div className="space-y-2">
          <div className="flex items-center gap-2 mb-2">
            <div className="p-2 rounded-lg bg-purple-100">
              <MessageSquare className="w-4 h-4 text-purple-700" />
            </div>
            <h3 className="font-semibold text-sm">Penutupan</h3>
          </div>
          <div className="p-4 rounded-lg bg-purple-50 border border-purple-200">
            <p className="text-sm text-purple-900 leading-relaxed italic">
              "{guide.closing}"
            </p>
          </div>
        </div>

        {/* Tips Section */}
        {guide.tips && (
          <div className="space-y-2">
            <div className="flex items-center gap-2 mb-2">
              <div className="p-2 rounded-lg bg-indigo-100">
                <Sparkles className="w-4 h-4 text-indigo-700" />
              </div>
              <h3 className="font-semibold text-sm">Tips untuk Anda</h3>
            </div>
            <div className="p-4 rounded-lg bg-indigo-50 border border-indigo-200">
              <p className="text-sm text-indigo-900 leading-relaxed">
                {guide.tips}
              </p>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
